### ISSUE TITLE
Any plan to release code?

### ISSUE THREAD

**Issue by chowkamlee81** [ziweiWWANG/AKF#2]
@ziweiWWANG ,

Do you any plans to release code going forward?

**Comment by ziweiWWANG** [comment]
Thanks for your interest. Yes, we will release the code. 
Since we are continuously working on the project and adding some new features, the code has not been rewritten to make it easier to access for other researchers, which means it is not ready to be officially released. If you are keen to evaluate our method right now, I can share with you some source code, but they are not cleaned up properly at this stage. Otherwise, you can wait for a bit longer, and we will officially release the code in the future. Please let me know if you have any other questions. Have a nice day :)

**Comment by chowkamlee81** [comment]
@ziweiWWANG 

Thanks for your response. 
Can you share your existing code even though not cleaned up to my mail id chowkamlee81@gmail.com

**Comment by chowkamlee81** [comment]
@ziweiWWANG 
Can you kindly share uncleaned version of your code to my mail id chowkamlee81@gmail.com

**Comment by ziweiWWANG** [comment]
Code released.
